services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "80:8080"
    depends_on:
      - db
    container_name: delivery-backend
    volumes:
      - ./src/main/java:/delivery/src/main/java  # ✅ Java 소스 코드 동기화
      - ./src/main/resources:/delivery/src/main/resources  # ✅ 설정 파일 동기화
    working_dir: /delivery
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "400M"

  db:
    image: postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=delivery
    container_name: delivery-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "300M"

  redis:
    image: redis:latest
    container_name: delivery-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "150M"
    command: [ "redis-server", "--appendonly", "yes", "--bind", "0.0.0.0" ]  # ✅ 외부 접근 허용

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=myuser@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=mypassword
    ports:
      - "8088:80"
    container_name: delivery-pgadmin
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "150M"

volumes:
  db_data:
  redis_data:  # ✅ Redis 볼륨 추가