spring:
  application:
    name:
      delivery

  datasource:
    url: jdbc:postgresql://delivery-db:5432/delivery
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
